version: "3.10"

networks:
  verim_network:
    name: verim_network
  verim_auth_network:
    name: verim_auth_network

services:
  db:
    image: postgres:15.4
    container_name: ${CONTAINER_PREFIX}-db
    volumes:
      - verim_auth_db_data:/var/lib/postgresql/data
      - ${MAIN_PATH}/configs/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - verim_network
      - verim_auth_network
    ports:
      - "127.0.0.1:7433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  auth:
    container_name: ${CONTAINER_PREFIX}-auth
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    working_dir: ${DEFAULT_SERVICE_DIR}
    env_file:
      - .env
    volumes:
      # app dir
      - ./auth/:${DEFAULT_SERVICE_DIR}
      # web stuff
      - ${STATIC_PATH}:/static
      - ${MEDIA_PATH}:/media
      - ${LOG_PATH}:/logs
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "50051:50051"
    networks:
      - verim_network
      - verim_auth_network
    restart: unless-stopped

volumes:
  verim_auth_db_data:
    name: verim_auth_db_data
